### ISSUE TITLE
Can't read elevation layer...

### ISSUE THREAD

**Issue by S-E-1** [JMG30/flight_planner#11]
Hello,

I downloaded Swiss Topo Alti3D files, inserted them as raster layer in QGIS, they are displayed at the right coordinates, altitude values are also correct on a grey scale.

The issue is when I try to "Get (terrain heights) from DTM", max and min textboxes are filled with NULL values.
When I check "Increase due to landform", I get an error message : "Type float numbers".

I tried to reproject (warp) the raster's CRS to EPSG:3857 (used for the other layers), but the issue is the same.
I also tried different .tiffs from the same source (one attached) to no avail.
Layers "Photos" and "Projection centres" are still created, but checking "Terrain following" doesn't work, and Z values remain constant, with correct heights.

Attached are the Error_log.txt file and a sample elevation .tiff.

Any idea, maybe the geotiff is not in the right format ?

[swissalti3d_2021_2492-1114_0.5_2056_5728.zip](https://github.com/JMG30/flight_planner/files/8444968/swissalti3d_2021_2492-1114_0.5_2056_5728.zip
[Error_log.txt](https://github.com/JMG30/flight_planner/files/8444995/Error_log.txt)
)

**Comment by JMG30** [comment]
Hi @S-E-1

I'm not sure what may cause this problem. Unfortunately attached error_log file did not help me as well.

I've tested the raster you sent and everything works fine:
![obraz](https://user-images.githubusercontent.com/44444960/162291749-63fa646a-5a1e-419a-8ec3-0a2947654296.png)

My test_area_of_interest.shp file have the same CRS as the raster you've sent.

Could you tell me more about your Area Of Interest.shp file or maybe you can send it to me like DTM? What are the camera parameters, GSD etc?

**Comment by S-E-1** [comment]
Now I just found that **it only works if the area of interest polygon is on a scratch layer**... the issue is when the AoI is on a shapefile layer the issues with terrain elevation are still as described...
Apparently reading elevations should aslo work with a saved shapefile layer, based on your post ?
Not sure why the error_log mention string about gsd, I'm using integers only.
It would just come handy for me to save the same layers with AoI polygons, instead redrawing every time on scratch layers, since I mostly 'survey' the same areas.

**Comment by JMG30** [comment]
Sorry, I'm a little confused, becuase I have QGIS in my native language and I'm not sure what you're mean saying _**scratch layer**_ and _**shapefile layer**_. Scratch layer is a layer creating by Layer - > Create layer -> **New Temporary Scratch Layer** and Shapefile layer is a layer created by Layer - > Create layer -> **New Shapefile Layer** ? Or am I wrong?

I really want to know, because for me layers created both ways work fine with my plugin. It might seem like a silly question for you, but I have to recreate problem to have an opportunity to settle the issue in the future.

If there is a chance to send me a problematic layer I would really appreciate it. It doesn't have to be the area of your 'surveys' if you don't want reveal it.

PS What version of QGIS do you use?

**Comment by S-E-1** [comment]
That's exactly what I'm talking about, but now I think I have narrowed it down... **the issue is that I didn't SAVE the shapefile layer correctly before using the plugin** ! The part without 'Terrain following' handled correctly, as well as the AoI polygons on scratch layers, so I didn't think the problem was on my side !

I saved it to send you the .shp file, and only at this point everything worked fine ! ...so I don't need to send the file !

I'm using QGIS 3.22(.1), Win10 pro, and trying to reproduce my error again a few more times, it either crashes QGIS or handles as described in my 1st posts... (again, only with unsaved .shp files !)

Sorry for your time, my bad ! Thanks for your help ! I don't think you can do anything about this... Just in case you'd want to check, create a new shapefile, draw a polygon, and use the DTM options as described...

**Comment by JMG30** [comment]
Ok, thanks for your explanation. I'm glad that problem was "solved".
