### ISSUE TITLE
Python warning np.float deprecated

### ISSUE THREAD

**Issue by WarrenSchultz** [JMG30/flight_planner#13]
Low priority, since it works as-is for now, but just to put it on the list for tracking, since I don't see it already.

WARNING    warning:{userpath}/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flight_planner\functions.py:229: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
             Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
              Z = ndimage.map_coordinates(Z_DTM, rc_array, output=np.float)

**Comment by JMG30** [comment]
Ok, thanks for your attention, I'll keep that in mind and will change it in a future release.
