### ISSUE TITLE
Negative overlap

### ISSUE THREAD

**Issue by kpauly** [JMG30/flight_planner#16]
A previous version of the QGIS Flight Planner plug-in allowed unbound negative overlap values (e.g., -300). This is not the case anymore in the latest version: the minimal overlap value is now 0. As this was a very interesting and rarely seen feature, allowing sparse but regular image acquisition planning, would it be possible to reinstate this feature (and possibly raise a warning message to prevent unintended use)?

**Comment by JMG30** [comment]
It was rather a bug than a feature and I'm not gonna restore it.

But if you liked it, here is revised version of UI file that allows to negative values. Just replace it with existing one.
[flight_planner_dialog_base.zip](https://github.com/JMG30/flight_planner/files/9990143/flight_planner_dialog_base.zip)

If you want even bigger negative values just change the numbers in line 250 and 276 of the file.
