### ISSUE TITLE
Flight Direction greater than 0.

### ISSUE THREAD

**Issue by jfng74** [JMG30/flight_planner#17]
Hello!

Flight Planner return error when changing dial flight direction in QGIS version 3.30.0-'s-Hertogenbosch.

In the python console, the plugin return this : 

QgsGeometry.convertToType(): argument 1 has unexpected type 'int' Traceback (most recent call last):
  File "/home/caribou/.local/share/QGIS/QGIS3/profiles/default/python/plugins/flight_planner/flight_planner_dialog.py", line 569, in on_pushButtonRunDesign_clicked
    a, b, a2, b2, Dx, Dy = bounding_box_at_angle(angle,
  File "/home/caribou/.local/share/QGIS/QGIS3/profiles/default/python/plugins/flight_planner/functions.py", line 441, in bounding_box_at_angle
    for vertex in range(len(geom.convertToType(1).asPolyline())):
TypeError: QgsGeometry.convertToType(): argument 1 has unexpected type 'int'

With angle set to 0, the plugin works!

Thanks

Jean-Francois

**Comment by JMG30** [comment]
Hi

QGIS developers changed some method and therefore the plugin was broken. I already fixed it, you can download the upated repository or wait a few days for the update to be accepted in the official QGIS plugin repository.

Thanks for report the issue.

**Comment by jfng74** [comment]
Perfect!

Thank you!  It's a great plugin to use!

Have a nice day!

JF
