### ISSUE TITLE
Focal length and sensor pixel size

### ISSUE THREAD

**Issue by JMM385** [JMG30/flight_planner#19]
Hi there!

I'd like to know how to estimate focal length and sensor pixel size of my drone (DJI MINI 3 PRO) as it isn't part of the default set of cameras and I couldn't find it in DJI's specifications as well.

Thanks in advance for such a great tool.

**Comment by geobrun** [comment]
Hi @JMM385,

You can use this formula to calculate the sensor pixel size: width of the sensor in millimetres / image width in pixels * 1000 ([cf. the end of this article](https://www.ephotozine.com/article/camera-image-sensor-pixel-size-explained-29652)).

For the calculation, you can find the information you need on these webpages:
- https://hotrodcameras.com/dji-mini-3-pro-with-dji-rc-remote/
- https://www.dpreview.com/articles/4159871805/making-sensor-sizes-less-misleading

So, if you want to shoot in 48MP, here is the calculation : 10mm / 8064px * 1000 = 1.24µm (confirmed by this [website](https://www.dpreview.com/news/9341131930/dji-unveils-mini-3-pro-drone-with-4k-60-video-48mp-stills-obstacle-avoidance-sensors-more)).

Through the second link, you can find that the focal length of the Dji Mini 3 Pro is 24mm.

Unfortunately, I will not be able to answer more question in the coming days as I will be in holiday for 3 weeks from this afternoon! ;)

**Comment by JMM385** [comment]
Thank you for your quick response. This is more than helpful.

Enjoy your holidays!
