### ISSUE TITLE
Issue with Litchi

### ISSUE THREAD

**Issue by Onoteis** [JMG30/flight_planner#4]
First of all, thanks a lot for this pluggin !

Is there a way to make the plans compatible with Litchi (flight app) ?

**Comment by JMG30** [comment]
I'm glad you like it :)

I never used Litchi so my knowledge about this app is equal zero, but after some quick research I could only recommend you to:
1. Convert Above Sea Level values to Above Ground Level (after you made flight plan use Sample raster values tool and then substract these values from Alt.ASL. If you want to make flight at one altidude for whole project, just set minimum and maximum terrain heights to 0),
2. Convert the X,Y coordinates to WGS84 coordinates (latitudes, longitudes, for example: Vector -> Geometry tools -> Add geometry attributes (don't forget to set QGIS project's EPSG to 4326),
3. Export attribute table to .csv (Export -> Save as...)

Then it looks like you should do this: https://mavicpilots.com/threads/litchi-import-csv-waypoints.73943/ 
Make sure the waypoints are in the correct order and don't forget to set waypoints Action: Take Photo? (I saw something like this in one video on yt, but you probably know better than me).

Hope I've been helpful

**Comment by JMG30** [comment]
@Onoteis 
If you're still interested @pdfinn has created tool to convert plugin's output to Litchi mission: https://github.com/pdfinn/flightplan2litchimission

**Comment by piahoo** [comment]
Hi! thanks a lot for this pluggin !
Have you thought about adding an export option to Litchi?

**Comment by pdfinn** [comment]
@piahoo the tool mentioned by @JMG30 (https://github.com/pdfinn/flightplan2litchimission , above) converts a flight plan created by the plugin to a Litchi mission.  A tutorial video is also available here: https://www.youtube.com/watch?v=6bH01lr41ig&t=201s there are a few steps involved, but once you understand the flow, its pretty quick and easy.
