### ISSUE TITLE
Error_log.txt  / NoneType: None

### ISSUE THREAD

**Issue by bluebird1250** [JMG30/flight_planner#5]
Interesting plugin!

When pressing "Accept", I get the message

``` "Error: See error log file in plugin folder"```

The Error_log.txt says:
```
Tue Sep 20 15:59:11 2020
NoneType: None
```

I use Qgis 3.14 / Linux Mint 20
Installed version of flight planner plugin:	0.5.3

Any hints are welcome

**Comment by JMG30** [comment]
First I would like to know which of the "Accept" buttons? The one for the flight assessment or the one for the flight planning? I guess the first one. If so, please make sure you have entered all camera parameters, DTM is ok and that the indicated attirubtes Altitude, Omega, Phi, Kappa from attribute table are also ok.

If you could describe the problem in more detail, take a screenshot with the plugin parameters filled in, or even send me the data you are working on it would be very helpful.

**Comment by bluebird1250** [comment]
Thanks to your answer. I see that I've completely misunderstood the GUI.
I thought that it was all pre-processing, but now I understand this:

"Flight control" is the same as "Post-processing (done after flight)
The rest of the GUI is pre-processing (before flight)

Is  this correctly understood?
(I was now able to make a "pre-processing", generating the points with planned projection coordinates)

I would gladly provide my data, but due to the misunderstanding, I think this is not necessary

**Comment by JMG30** [comment]
Yes you're right. I just want to notice that you can use pre-processed or actual flight data in post-processing. If everything is clear, I'll close the issue.

**Comment by bluebird1250** [comment]
Thanks! 
You can close the issue.
