### ISSUE TITLE
Unknow error log

### ISSUE THREAD

**Issue by Edwrom** [JMG30/flight_planner#6]
When selecting the parameters in flight control, and check these boxes: photo footprint, logical sum ,, gsd map, and give the acceptor
an error message appears.
I looked for the file and this is what it contains : 
"_Fri Feb  5 22:23:52 2021
Traceback (most recent call last):
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/flight_planner/flight_planner_dialog.py", line 1375, in on_pBaccept_clicked
    {'INPUT':self.pathLine,
AttributeError: 'FlightPlannerDialog' object has no attribute 'pathLine'
"_

Qgis V 3.16.3 running on Linux mint 20.1

**Comment by JMG30** [comment]
Are you sure you're clicking the correct Accept button? It seems to me, that you've clicked the one on the right side. If you want to do a flight control you should click the one at the bottom.

Don't forget to load DTM, camera parameters and projecetion centers with their External Orientation parameters.
