### ISSUE TITLE
Scanners

### ISSUE THREAD

**Issue by alg8598** [JMG30/flight_planner#8]
Hello, would it be possible to add flight track writing and add scanner in camera model ? 
I assume one has to compute flight line before and assign flight time to an across track camera with 1 pixel along ?
Thanks for your ideas !
Interested into hyperspectral and thermal scanners, i can pass though specs.
A.

**Comment by JMG30** [comment]
Now in spare time I focus on optimising of plugin and improving the interface, but maybe in the future i could add something about scanners. The problem is that my knowledge of scanners is very sketchy, so I should delve into the topic first - in other words it won't be soon.
If you have any interesting papers about scanners' flight planning, feel free to send them to me.

**Comment by alg8598** [comment]
Hi, for sure!

The best imprvement should to add flight line vectors for flight time 
duration computation. THen user can precioulsy calculate filght duration 
with each turns, that is set in a std way, generally 3 minutes / not 
more than 20° incination for avoiding  GNSS signals loss.

About scanners, I can send you the one we're iterested in, it's actually 
cross track FOV per 1 pixel along track * scan rate at given flight 
speed. Thus you ould significantly improve to Lidar and hyperspectral.



Arnaud Le guellec - Sales manager & CEO - LATITUDE GEOSYSTEMS SAS
Centre d'affaires du Lac
2, rue de Malleville - 95880 Enghien les Bains, FRANCE
Tel: +33 (0)967528345 - Mobile +33(0)643394459
skype : aleguellec
E-mail : ***@***.***
http://www.latitude-geosystems.com

Le 07/06/2021 à 23:05, JMG30 a écrit :

**Comment by alg8598** [comment]
Hi, for sure!

The best improvement should to add flight line vectors for flight time duration computation. Then user can precioulsy calculate flight duration with each turns, that is set in a std way, generally 3 minutes / not more than 20° inclination for avoiding  GNSS signals loss.

About scanners, I can send you the one we're interested in, it's actually cross track FOV per 1 pixel along track * scan rate at given flight speed. Thus you could significantly improve to Lidar and hyperspectral.

**Comment by alg8598** [comment]
That one is a push-broom hyperspectral scanner:
40° FOV, 1500 pixels across track:
https://itres.com/wp-content/uploads/2019/09/CASI1500.pdf
